### ISSUE TITLE
increase findability with open KnowHow

### ISSUE THREAD

**Issue by amchagas** [gpask/PiSpy#5]
More of a nice to have, than an essential part of your documentation:
[Open knowhow](https://www.internetofproduction.org/open-know-how) is a project making it easier to find open source hardware projects. 

It is quite simple to add projects to their database, and I think it is quite useful for other people actually finding this project

**Comment by gpask** [comment]
I've completed the OKH manifest and have the .yml file. What should I do now?

**Comment by amchagas** [comment]
Now you should add the file this repo (at root level is fine), and add the link to the file to this list https://github.com/iop-alliance/okh-search/blob/master/projects_okhs.csv

**Comment by gpask** [comment]
Thanks, I believe I did that correctly by editing the file and submitting the change as a Pull Request. That's it, right? Such a GitHub noob right now...

**Comment by amchagas** [comment]
All good! I think the bot hooked up to that repo has already caught your update
